"""8e

Revision ID: 0fe5aae26c94
Revises: a9377459590f
Create Date: 2018-07-23 22:57:23.012719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fe5aae26c94'
down_revision = 'a9377459590f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warnsqls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('sql_statement', sa.Text(), nullable=True),
    sa.Column('sql_parameters', sa.Text(), nullable=True),
    sa.Column('sql_duration', sa.Integer(), nullable=True),
    sa.Column('sql_context', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warnsqls_timestamp'), 'warnsqls', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_warnsqls_timestamp'), table_name='warnsqls')
    op.drop_table('warnsqls')
    # ### end Alembic commands ###
