"""16

Revision ID: 1b2b0d93a8ba
Revises: 5ae2353a173c
Create Date: 2018-08-21 16:10:28.530756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b2b0d93a8ba'
down_revision = '5ae2353a173c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('celery_tasks', sa.Column('task_percent', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('celery_tasks', 'task_percent')
    # ### end Alembic commands ###
