"""13

Revision ID: 28d0db10d49e
Revises: f05f3935304d
Create Date: 2018-07-30 02:37:27.572709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28d0db10d49e'
down_revision = 'f05f3935304d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('math_papers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('q_args', sa.String(length=64), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('score_flag', sa.Boolean(), nullable=True),
    sa.Column('isInt', sa.Boolean(), nullable=True),
    sa.Column('minval', sa.Integer(), nullable=True),
    sa.Column('maxval', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=64), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_math_papers_timestamp'), 'math_papers', ['timestamp'], unique=False)
    op.create_table('math_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=True),
    sa.Column('a', sa.Float(), nullable=True),
    sa.Column('b', sa.Float(), nullable=True),
    sa.Column('op', sa.Integer(), nullable=True),
    sa.Column('val', sa.Float(), nullable=True),
    sa.Column('key', sa.Float(), nullable=True),
    sa.Column('result', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['math_papers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('math_questions')
    op.drop_index(op.f('ix_math_papers_timestamp'), table_name='math_papers')
    op.drop_table('math_papers')
    # ### end Alembic commands ###
