"""11

Revision ID: 66eaedf79de8
Revises: 0fe5aae26c94
Create Date: 2018-07-25 23:20:52.344260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66eaedf79de8'
down_revision = '0fe5aae26c94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jobname', sa.String(length=64), nullable=True),
    sa.Column('func', sa.String(length=64), nullable=True),
    sa.Column('args', sa.String(length=64), nullable=True),
    sa.Column('jobtype', sa.String(length=64), nullable=True),
    sa.Column('trigger', sa.String(length=64), nullable=True),
    sa.Column('year', sa.String(length=64), nullable=True),
    sa.Column('month', sa.String(length=64), nullable=True),
    sa.Column('day', sa.String(length=64), nullable=True),
    sa.Column('hour', sa.String(length=64), nullable=True),
    sa.Column('minute', sa.String(length=64), nullable=True),
    sa.Column('second', sa.String(length=64), nullable=True),
    sa.Column('week', sa.String(length=64), nullable=True),
    sa.Column('day_of_week', sa.String(length=64), nullable=True),
    sa.Column('last_timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job')
    # ### end Alembic commands ###
