"""14

Revision ID: c366c5c7cc9b
Revises: 57a9674a6ad5
Create Date: 2018-08-13 14:25:00.084383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c366c5c7cc9b'
down_revision = '57a9674a6ad5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('math_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('isInt', sa.Boolean(), nullable=True),
    sa.Column('minval', sa.Integer(), nullable=True),
    sa.Column('maxval', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=64), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('math_configs')
    # ### end Alembic commands ###
