"""12

Revision ID: f05f3935304d
Revises: c349b2379cca
Create Date: 2018-07-29 20:35:12.340570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f05f3935304d'
down_revision = 'c349b2379cca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('math_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('q_args', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('a', sa.Float(), nullable=True),
    sa.Column('b', sa.Float(), nullable=True),
    sa.Column('op', sa.Integer(), nullable=True),
    sa.Column('val', sa.Float(), nullable=True),
    sa.Column('key', sa.Float(), nullable=True),
    sa.Column('result', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_math_questions_timestamp'), 'math_questions', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_math_questions_timestamp'), table_name='math_questions')
    op.drop_table('math_questions')
    # ### end Alembic commands ###
